// swift-tools-version: 5.10
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "Delux",
    platforms: [.iOS(.v14)],
    products: [
        // Products define the executables and libraries a package produces, making them visible to other packages.
        .library(
            name: "Delux",
            targets: ["Delux",
                      "App",
                      "FBLPromises",
                      "FirebaseABTesting",
                      "FirebaseAppCheckInterop",
                      "FirebaseAuth",
                      "FirebaseAuthInterop",
                      "FirebaseCore",
                      "FirebaseCoreExtension",
                      "FirebaseCoreInternal",
                      "FirebaseDatabase",
                      "FirebaseFirestore",
                      "FirebaseFirestoreInternal",
                      "FirebaseInstallations",
                      "FirebasePerformance",
                      "FirebaseRemoteConfig",
                      "FirebaseRemoteConfigInterop",
                      "FirebaseSessions",
                      "FirebaseSharedSwift",
                      "FlutterPluginRegistrant",
                      "GTMSessionFetcher",
                      "GoogleDataTransport",
                      "GoogleUtilities",
                      "OrderedSet",
                      "Promises",
                      "RecaptchaInterop",
                      "absl",
                      "cloud_firestore",
                      "firebase_auth",
                      "firebase_core",
                      "firebase_database",
                      "firebase_performance",
                      "flutter_inappwebview_ios",
                      "grpc",
                      "grpcpp",
                      "leveldb",
                      "nanopb",
                      "openssl_grpc",
                    ]),
    ],
    targets: [
        // Targets are the basic building blocks of a package, defining a module or a test suite.
        // Targets can depend on other targets in this package and products from dependencies.
        .target(name: "Delux"),
        .binaryTarget(name: "App", path: "artifacts/App.xcframework"),
        .binaryTarget(name: "FBLPromises", path: "artifacts/FBLPromises.xcframework"),
        .binaryTarget(name: "FirebaseABTesting", path: "artifacts/FirebaseABTesting.xcframework"),
        .binaryTarget(name: "FirebaseAppCheckInterop", path: "artifacts/FirebaseAppCheckInterop.xcframework"),
        .binaryTarget(name: "FirebaseAuth", path: "artifacts/FirebaseAuth.xcframework"),
        .binaryTarget(name: "FirebaseAuthInterop", path: "artifacts/FirebaseAuthInterop.xcframework"),
        .binaryTarget(name: "FirebaseCore", path: "artifacts/FirebaseCore.xcframework"),
        .binaryTarget(name: "FirebaseCoreExtension", path: "artifacts/FirebaseCoreExtension.xcframework"),
        .binaryTarget(name: "FirebaseCoreInternal", path: "artifacts/FirebaseCoreInternal.xcframework"),
        .binaryTarget(name: "FirebaseDatabase", path: "artifacts/FirebaseDatabase.xcframework"),
        .binaryTarget(name: "FirebaseFirestore", path: "artifacts/FirebaseFirestore.xcframework"),
        .binaryTarget(name: "FirebaseFirestoreInternal", path: "artifacts/FirebaseFirestoreInternal.xcframework"),
        .binaryTarget(name: "FirebaseInstallations", path: "artifacts/FirebaseInstallations.xcframework"),
        .binaryTarget(name: "FirebasePerformance", path: "artifacts/FirebasePerformance.xcframework"),
        .binaryTarget(name: "FirebaseRemoteConfig", path: "artifacts/FirebaseRemoteConfig.xcframework"),
        .binaryTarget(name: "FirebaseRemoteConfigInterop", path: "artifacts/FirebaseRemoteConfigInterop.xcframework"),
        .binaryTarget(name: "FirebaseSessions", path: "artifacts/FirebaseSessions.xcframework"),
        .binaryTarget(name: "FirebaseSharedSwift", path: "artifacts/FirebaseSharedSwift.xcframework"),
        .binaryTarget(name: "FlutterPluginRegistrant", path: "artifacts/FlutterPluginRegistrant.xcframework"),
        .binaryTarget(name: "GTMSessionFetcher", path: "artifacts/GTMSessionFetcher.xcframework"),
        .binaryTarget(name: "GoogleDataTransport", path: "artifacts/GoogleDataTransport.xcframework"),
        .binaryTarget(name: "GoogleUtilities", path: "artifacts/GoogleUtilities.xcframework"),
        .binaryTarget(name: "OrderedSet", path: "artifacts/OrderedSet.xcframework"),
        .binaryTarget(name: "Promises", path: "artifacts/Promises.xcframework"),
        .binaryTarget(name: "RecaptchaInterop", path: "artifacts/RecaptchaInterop.xcframework"),
        .binaryTarget(name: "absl", path: "artifacts/absl.xcframework"),
        .binaryTarget(name: "cloud_firestore", path: "artifacts/cloud_firestore.xcframework"),
        .binaryTarget(name: "firebase_auth", path: "artifacts/firebase_auth.xcframework"),
        .binaryTarget(name: "firebase_core", path: "artifacts/firebase_core.xcframework"),
        .binaryTarget(name: "firebase_database", path: "artifacts/firebase_database.xcframework"),
        .binaryTarget(name: "firebase_performance", path: "artifacts/firebase_performance.xcframework"),
        .binaryTarget(name: "flutter_inappwebview_ios", path: "artifacts/flutter_inappwebview_ios.xcframework"),
        .binaryTarget(name: "grpc", path: "artifacts/grpc.xcframework"),
        .binaryTarget(name: "grpcpp", path: "artifacts/grpcpp.xcframework"),
        .binaryTarget(name: "leveldb", path: "artifacts/leveldb.xcframework"),
        .binaryTarget(name: "nanopb", path: "artifacts/nanopb.xcframework"),
        .binaryTarget(name: "openssl_grpc", path: "artifacts/openssl_grpc.xcframework"),


        
    ]
)
