// swift-tools-version: 5.10
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "delux-ios",
    products: [
        // Products define the executables and libraries a package produces, making them visible to other packages.
        .library(
            name: "delux-ios",
            targets: ["delux-ios"]),
    ],
    targets: [
    .target(
                name: "delux-ios",
                dependencies: [
                    "App",
                    "AppAuth",
                    "FBLPromises",
                    "FirebaseABTesting",
                    "FirebaseAppCheckInterop",
                    "FirebaseAuth",
                    "FirebaseCore",
                    "FirebaseCoreExtension",
                    "FirebaseCoreInternal",
                    "FirebaseCrashlytics",
                    "FirebaseDatabase",
                    "FirebaseDynamicLinks",
                    "FirebaseFirestore",
                    "FirebaseFirestoreInternal",
                    "FirebaseInAppMessaging",
                    "FirebaseInstallations",
                    "FirebaseMessaging",
                    "FirebasePerformance",
                    "FirebaseRemoteConfig",
                    "FirebaseRemoteConfigInterop",
                    "FirebaseSessions",
                    "FirebaseSharedSwift",
                    "Flutter",
                    "FlutterPluginRegistrant",
                    "GTMAppAuth",
                    "GTMSessionFetcher",
                    "GoogleDataTransport",
                    "GoogleSignIn",
                    "GoogleUtilities",
                    "OrderedSet",
                    "Promises",
                    "RecaptchaInterop",
                    "absl",
                    "cloud_firestore",
                    "firebase_analytics",
                    "firebase_auth",
                    "firebase_core",
                    "firebase_crashlytics",
                    "firebase_database",
                    "firebase_dynamic_links",
                    "firebase_in_app_messaging",
                    "firebase_messaging",
                    "firebase_performance",
                    "firebase_remote_config",
                    "flutter_config",
                    "flutter_inappwebview_ios",
                    "google_sign_in_ios",
                    "grpc",
                    "grpcpp",
                    "leveldb",
                    "nanopb",
                    "openssl_grpc",
                    "sign_in_with_apple"
                ]
            ),
    .binaryTarget(name: "App", path: "./dependencies/App.xcframework"),
    .binaryTarget(name: "AppAuth", path: "./dependencies/AppAuth.xcframework"),
    .binaryTarget(name: "FBLPromises", path: "./dependencies/FBLPromises.xcframework"),
    .binaryTarget(name: "FirebaseABTesting", path: "./dependencies/FirebaseABTesting.xcframework"),
    .binaryTarget(name: "FirebaseAppCheckInterop", path: "./dependencies/FirebaseAppCheckInterop.xcframework"),
    .binaryTarget(name: "FirebaseAuth", path: "./dependencies/FirebaseAuth.xcframework"),
    .binaryTarget(name: "FirebaseCore", path: "./dependencies/FirebaseCore.xcframework"),
    .binaryTarget(name: "FirebaseCoreExtension", path: "./dependencies/FirebaseCoreExtension.xcframework"),
    .binaryTarget(name: "FirebaseCoreInternal", path: "./dependencies/FirebaseCoreInternal.xcframework"),
    .binaryTarget(name: "FirebaseCrashlytics", path: "./dependencies/FirebaseCrashlytics.xcframework"),
    .binaryTarget(name: "FirebaseDatabase", path: "./dependencies/FirebaseDatabase.xcframework"),
    .binaryTarget(name: "FirebaseDynamicLinks", path: "./dependencies/FirebaseDynamicLinks.xcframework"),
    .binaryTarget(name: "FirebaseFirestore", path: "./dependencies/FirebaseFirestore.xcframework"),
    .binaryTarget(name: "FirebaseFirestoreInternal", path: "./dependencies/FirebaseFirestoreInternal.xcframework"),
    .binaryTarget(name: "FirebaseInAppMessaging", path: "./dependencies/FirebaseInAppMessaging.xcframework"),
    .binaryTarget(name: "FirebaseInstallations", path: "./dependencies/FirebaseInstallations.xcframework"),
    .binaryTarget(name: "FirebaseMessaging", path: "./dependencies/FirebaseMessaging.xcframework"),
    .binaryTarget(name: "FirebasePerformance", path: "./dependencies/FirebasePerformance.xcframework"),
    .binaryTarget(name: "FirebaseRemoteConfig", path: "./dependencies/FirebaseRemoteConfig.xcframework"),
    .binaryTarget(name: "FirebaseRemoteConfigInterop", path: "./dependencies/FirebaseRemoteConfigInterop.xcframework"),
    .binaryTarget(name: "FirebaseSessions", path: "./dependencies/FirebaseSessions.xcframework"),
    .binaryTarget(name: "FirebaseSharedSwift", path: "./dependencies/FirebaseSharedSwift.xcframework"),
    .binaryTarget(name: "Flutter", path: "./dependencies/Flutter.xcframework"),
    .binaryTarget(name: "FlutterPluginRegistrant", path: "./dependencies/FlutterPluginRegistrant.xcframework"),
    .binaryTarget(name: "GTMAppAuth", path: "./dependencies/GTMAppAuth.xcframework"),
    .binaryTarget(name: "GTMSessionFetcher", path: "./dependencies/GTMSessionFetcher.xcframework"),
    .binaryTarget(name: "GoogleDataTransport", path: "./dependencies/GoogleDataTransport.xcframework"),
    .binaryTarget(name: "GoogleSignIn", path: "./dependencies/GoogleSignIn.xcframework"),
    .binaryTarget(name: "GoogleUtilities", path: "./dependencies/GoogleUtilities.xcframework"),
    .binaryTarget(name: "OrderedSet", path: "./dependencies/OrderedSet.xcframework"),
    .binaryTarget(name: "Promises", path: "./dependencies/Promises.xcframework"),
    .binaryTarget(name: "RecaptchaInterop", path: "./dependencies/RecaptchaInterop.xcframework"),
    .binaryTarget(name: "absl", path: "./dependencies/absl.xcframework"),
    .binaryTarget(name: "cloud_firestore", path: "./dependencies/cloud_firestore.xcframework"),
    .binaryTarget(name: "firebase_analytics", path: "./dependencies/firebase_analytics.xcframework"),
    .binaryTarget(name: "firebase_auth", path: "./dependencies/firebase_auth.xcframework"),
    .binaryTarget(name: "firebase_core", path: "./dependencies/firebase_core.xcframework"),
    .binaryTarget(name: "firebase_crashlytics", path: "./dependencies/firebase_crashlytics.xcframework"),
    .binaryTarget(name: "firebase_database", path: "./dependencies/firebase_database.xcframework"),
    .binaryTarget(name: "firebase_dynamic_links", path: "./dependencies/firebase_dynamic_links.xcframework"),
    .binaryTarget(name: "firebase_in_app_messaging", path: "./dependencies/firebase_in_app_messaging.xcframework"),
    .binaryTarget(name: "firebase_messaging", path: "./dependencies/firebase_messaging.xcframework"),
    .binaryTarget(name: "firebase_performance", path: "./dependencies/firebase_performance.xcframework"),
    .binaryTarget(name: "firebase_remote_config", path: "./dependencies/firebase_remote_config.xcframework"),
    .binaryTarget(name: "flutter_config", path: "./dependencies/flutter_config.xcframework"),
    .binaryTarget(name: "flutter_inappwebview_ios", path: "./dependencies/flutter_inappwebview_ios.xcframework"),
    .binaryTarget(name: "google_sign_in_ios", path: "./dependencies/google_sign_in_ios.xcframework"),
    .binaryTarget(name: "grpc", path: "./dependencies/grpc.xcframework"),
    .binaryTarget(name: "grpcpp", path: "./dependencies/grpcpp.xcframework"),
    .binaryTarget(name: "leveldb", path: "./dependencies/leveldb.xcframework"),
    .binaryTarget(name: "nanopb", path: "./dependencies/nanopb.xcframework"),
    .binaryTarget(name: "openssl_grpc", path: "./dependencies/openssl_grpc.xcframework"),
    .binaryTarget(name: "sign_in_with_apple", path: "./dependencies/sign_in_with_apple.xcframework"),

            ]
)
